version: '2.1'
services:
  nginx:
    container_name: medev_nginx
    image: nginx:1.15.2-alpine
    mem_limit: 500m
    memswap_limit: 500m
    cpu_shares: 20
    ports:
      - "8080:80"
    networks:
      medev_net:
        ipv4_address: 10.15.0.100
    extra_hosts:
      # services
      php56: 10.15.0.4
      php71: 10.15.0.5
      php72: 10.15.0.6
      mysql: 10.15.0.20
      mongo: 10.15.0.21
      redis: 10.15.0.22
      rabbitmq: 10.15.0.23
    volumes:
      - ./../nginx:/image/
      - ./../nginx/files/nginx.conf:/etc/nginx/nginx.conf
      - ./../nginx/files/conf.d:/etc/nginx/conf.d
      - ~/Workspace/:/var/www/
