version: '2.1'
services:
  php72:
    container_name: medev_php72
    image: meio/php-dev:7.2.8
    mem_limit: 2g
    memswap_limit: 2g
    cpu_shares: 30
    privileged: true
    ports:
      - 8443:443 # nginx ssl
      - "2222:22" # ssh
      - 9003:9003 # xdebug
      - 9001:9001 # supervisor admin
      - 9110:9110 # php
    entrypoint: /image/start.sh

    volumes:
      - ./../php7:/image/

      - ~/Workspace/:/var/www/
      - ~/Workspace/data/php-log:/var/log/php

      - ./../php7/etc/sshd.conf:/etc/ssh/sshd_config

      - ~/.ssh:/root/.ssh
      - ./../php7/etc/zshrc:/root/.zshrc
      - ./../php7/etc/zsh/aliases.conf:/root/.aliases
      - ./../php7/etc/zsh/extra.conf:/root/.extra

      - ~/.ssh:/home/www-data/.ssh
      - ./../php7/etc/zshrc:/home/www-data/.zshrc
      - ./../php7/etc/zsh/aliases.conf:/home/www-data/.aliases
      - ./../php7/etc/zsh/extra.conf:/home/www-data/.extra

    networks:
      medev_net:
        ipv4_address: 10.15.0.6

    extra_hosts:
      # services
      php56: 10.15.0.4
      php71: 10.15.0.5
      php72: 10.15.0.6
      mysql: 10.15.0.20
      mongo: 10.15.0.21
      mongodb: 10.15.0.21
      redis: 10.15.0.22

      # local domain
      medev.local: 10.15.0.100
