version: '2.1'
services:
  php71:
    container_name: medev_php71
    image: meio/dev-php:7.1.20
    mem_limit: 2g
    memswap_limit: 2g
    cpu_shares: 30
    privileged: true
    ports:
      - 8443:443 # nginx ssl
      - "2222:22" # ssh
      - 9003:9003 # xdebug
      - 9001:9001 # supervisor admin
      - 9110:9110 # php
    entrypoint: /image/start.sh

    volumes:
      - ./../php7:/image/

      - ~/Workspace/:/var/www/
      - ~/Workspace/data/php-log:/var/log/php

      - ./../php7/etc/sshd.conf:/etc/ssh/sshd_config

      - ~/.ssh:/root/.ssh
      - ./../php7/etc/zshrc:/root/.zshrc
      - ./../php7/etc/zsh/aliases.conf:/root/.aliases
      - ./../php7/etc/zsh/extra.conf:/root/.extra

      - ~/.ssh:/home/www-data/.ssh
      - ./../php7/etc/zshrc:/home/www-data/.zshrc
      - ./../php7/etc/zsh/aliases.conf:/home/www-data/.aliases
      - ./../php7/etc/zsh/extra.conf:/home/www-data/.extra

      #- ./../php7/php/php.ini:/etc/php/7.1/fpm/php.ini
      #- ./../php7/php/modules/mongodb.ini:/etc/php/7.1/mods-available/mongodb.ini

      #- ./../php7/php/php-fpm.conf:/etc/php/7.1/fpm/php-fpm.conf
      #- ./../php7/php/pool:/etc/php/7.1/fpm/pool.d

      #- ./../php7/php/php.ini:/usr/local/etc/php/php.ini
      #- ./../php7/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf

    networks:
      medev_net:
        ipv4_address: 10.15.0.5

    extra_hosts:
      # services
      php56: 10.15.0.4
      php71: 10.15.0.5
      php72: 10.15.0.6
      mysql: 10.15.0.20
      mongo: 10.15.0.21
      mongodb: 10.15.0.21
      redis: 10.15.0.22
      rabbitmq: 10.15.0.23

      # local domain
      medev.local: 10.15.0.100
      #
      www-api.medev.local: 10.15.0.100
      #
      payment-api.medev.local: 10.15.0.100
      #
      config-api.medev.local: 10.15.0.100
      #
      location-api.medev.local: 10.15.0.100
      #
      myaccount-api.medev.local: 10.15.0.100
      #
      schedule-api.medev.local: 10.15.0.100
      #
      all-api.medev.local: 10.15.0.100
