version: '2.1'
services:
  rabbitmq:
    container_name: medev_rabbitmq
    image: tajawalcom/rabbitmq:3.7.3-management-alpine
    privileged: true
    mem_limit: 400m
    memswap_limit: 400m
    cpu_shares: 15
    environment:
      - RABBITMQ_DEFAULT_USER=it-admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 5772:5672
      - 5771:5671
      - 15671:15671
      - 15771:15771
      - 15672:15672
      - 15772:15772
    networks:
      medev_net:
        ipv4_address: 10.15.0.23
    volumes:
      - ./../rabbitmq:/image
      - ./../rabbitmq/files/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw
      - ./../rabbitmq/files/rq.config:/etc/rabbitmq/rq.config:rw
      - ./../rabbitmq/files/definitions.json:/etc/rabbitmq/definitions.json:rw
      - ./../rabbitmq/files/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf:rw
